/**
 * This class is generated by jOOQ
 */
package smht.kingstar.entities;

/**
 * This class is generated by jOOQ.
 *
 * A class modelling foreign key relationships between tables of the <code>smht</code> 
 * schema
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.4.4" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

	// -------------------------------------------------------------------------
	// IDENTITY definitions
	// -------------------------------------------------------------------------

	public static final org.jooq.Identity<smht.kingstar.entities.tables.records.UserInfoRecord, java.lang.Integer> IDENTITY_USER_INFO = Identities0.IDENTITY_USER_INFO;

	// -------------------------------------------------------------------------
	// UNIQUE and PRIMARY KEY definitions
	// -------------------------------------------------------------------------

	public static final org.jooq.UniqueKey<smht.kingstar.entities.tables.records.UserInfoRecord> KEY_USER_INFO_PRIMARY = UniqueKeys0.KEY_USER_INFO_PRIMARY;

	// -------------------------------------------------------------------------
	// FOREIGN KEY definitions
	// -------------------------------------------------------------------------


	// -------------------------------------------------------------------------
	// [#1459] distribute members to avoid static initialisers > 64kb
	// -------------------------------------------------------------------------

	private static class Identities0 extends org.jooq.impl.AbstractKeys {
		public static org.jooq.Identity<smht.kingstar.entities.tables.records.UserInfoRecord, java.lang.Integer> IDENTITY_USER_INFO = createIdentity(smht.kingstar.entities.tables.UserInfo.USER_INFO, smht.kingstar.entities.tables.UserInfo.USER_INFO.USER_ID);
	}

	private static class UniqueKeys0 extends org.jooq.impl.AbstractKeys {
		public static final org.jooq.UniqueKey<smht.kingstar.entities.tables.records.UserInfoRecord> KEY_USER_INFO_PRIMARY = createUniqueKey(smht.kingstar.entities.tables.UserInfo.USER_INFO, smht.kingstar.entities.tables.UserInfo.USER_INFO.USER_ID);
	}
}
