/**
 * This class is generated by jOOQ
 */
package smht.kingstar.entities;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.4.4" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Smht extends org.jooq.impl.SchemaImpl {

	private static final long serialVersionUID = -1337343866;

	/**
	 * The singleton instance of <code>smht</code>
	 */
	public static final Smht SMHT = new Smht();

	/**
	 * No further instances allowed
	 */
	private Smht() {
		super("smht");
	}

	@Override
	public final java.util.List<org.jooq.Table<?>> getTables() {
		java.util.List result = new java.util.ArrayList();
		result.addAll(getTables0());
		return result;
	}

	private final java.util.List<org.jooq.Table<?>> getTables0() {
		return java.util.Arrays.<org.jooq.Table<?>>asList(
			smht.kingstar.entities.tables.UserInfo.USER_INFO);
	}
}
