/**
 * This class is generated by jOOQ
 */
package smht.kingstar.entities;

/**
 * This class is generated by jOOQ.
 *
 * Convenience access to all tables in smht
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.4.4" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

	/**
	 * The table smht.user_info
	 */
	public static final smht.kingstar.entities.tables.UserInfo USER_INFO = smht.kingstar.entities.tables.UserInfo.USER_INFO;
}
