/**
 * This class is generated by jOOQ
 */
package smht.kingstar.entities.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.4.4" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class UserInfo extends org.jooq.impl.TableImpl<smht.kingstar.entities.tables.records.UserInfoRecord> {

	private static final long serialVersionUID = -281160289;

	/**
	 * The singleton instance of <code>smht.user_info</code>
	 */
	public static final smht.kingstar.entities.tables.UserInfo USER_INFO = new smht.kingstar.entities.tables.UserInfo();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<smht.kingstar.entities.tables.records.UserInfoRecord> getRecordType() {
		return smht.kingstar.entities.tables.records.UserInfoRecord.class;
	}

	/**
	 * The column <code>smht.user_info.user_id</code>.
	 */
	public final org.jooq.TableField<smht.kingstar.entities.tables.records.UserInfoRecord, java.lang.Integer> USER_ID = createField("user_id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * The column <code>smht.user_info.user_nm</code>.
	 */
	public final org.jooq.TableField<smht.kingstar.entities.tables.records.UserInfoRecord, java.lang.String> USER_NM = createField("user_nm", org.jooq.impl.SQLDataType.VARCHAR.length(50), this, "");

	/**
	 * The column <code>smht.user_info.user_cd</code>.
	 */
	public final org.jooq.TableField<smht.kingstar.entities.tables.records.UserInfoRecord, java.lang.String> USER_CD = createField("user_cd", org.jooq.impl.SQLDataType.VARCHAR.length(50), this, "");

	/**
	 * The column <code>smht.user_info.user_mm</code>.
	 */
	public final org.jooq.TableField<smht.kingstar.entities.tables.records.UserInfoRecord, java.lang.String> USER_MM = createField("user_mm", org.jooq.impl.SQLDataType.VARCHAR.length(50), this, "");

	/**
	 * Create a <code>smht.user_info</code> table reference
	 */
	public UserInfo() {
		this("user_info", null);
	}

	/**
	 * Create an aliased <code>smht.user_info</code> table reference
	 */
	public UserInfo(java.lang.String alias) {
		this(alias, smht.kingstar.entities.tables.UserInfo.USER_INFO);
	}

	private UserInfo(java.lang.String alias, org.jooq.Table<smht.kingstar.entities.tables.records.UserInfoRecord> aliased) {
		this(alias, aliased, null);
	}

	private UserInfo(java.lang.String alias, org.jooq.Table<smht.kingstar.entities.tables.records.UserInfoRecord> aliased, org.jooq.Field<?>[] parameters) {
		super(alias, smht.kingstar.entities.Smht.SMHT, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Identity<smht.kingstar.entities.tables.records.UserInfoRecord, java.lang.Integer> getIdentity() {
		return smht.kingstar.entities.Keys.IDENTITY_USER_INFO;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.UniqueKey<smht.kingstar.entities.tables.records.UserInfoRecord> getPrimaryKey() {
		return smht.kingstar.entities.Keys.KEY_USER_INFO_PRIMARY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.UniqueKey<smht.kingstar.entities.tables.records.UserInfoRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<smht.kingstar.entities.tables.records.UserInfoRecord>>asList(smht.kingstar.entities.Keys.KEY_USER_INFO_PRIMARY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public smht.kingstar.entities.tables.UserInfo as(java.lang.String alias) {
		return new smht.kingstar.entities.tables.UserInfo(alias, this);
	}

	/**
	 * Rename this table
	 */
	public smht.kingstar.entities.tables.UserInfo rename(java.lang.String name) {
		return new smht.kingstar.entities.tables.UserInfo(name, null);
	}
}
